apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - josemari16ingress.southeastasia.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - josemari16ingress.southeastasia.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-aks
    kind: ClusterIssuer
